
rbac:
  # Specifies whether RBAC resources should be created
  create: true


rules:
  external:
    - seriesQuery: 'container_cpu_usage_seconds_total'
      resources:
        overrides:
          kubernetes_namespace:
            resource: namespace
          kubernetes_pod_name:
            resource: pod
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: (sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>))
