apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1 # Number of replicas to create
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
      labels:
        app: backend
    spec:
      containers:
      # - name: frontend-app
      #   image: surlalwani/frontendimage:latest
      #   ports:
      #   - containerPort: 3000 # Port number to expose
      - name: backend-app
        image: surlalwani/zocketbackend:latest
        ports:
        - containerPort: 5000 # Port number to expose
        resources:
          requests:
            cpu: "100m"  # Specify the CPU request (e.g., 100 milli-CPUs)
          limits:
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000