apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpapods
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: backend-app
  minReplicas: 1
  maxReplicas: 5
  # metrics:
  #   - type: Pods
  #     pods:
  #       metricName: container_cpu_usage_seconds_total
  #       targetAverageValue: 50
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       averageUtilization: 50
  # - type: Pods
  #   pods:
  #     metricName: container_cpu_usage_seconds_total
  #     targetAverageValue: 50

  targetCPUUtilizationPercentage: 50