version: 0.2

phases:
  pre_build:
    commands:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=391423671772.dkr.ecr.us-east-1.amazonaws.com/test
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images.connect..
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

  # install:
  #   commands:
  #     #1. To assume a IAM role in CodeBuild build, uncomment below lines and replace role name
  #     # Create ~/.aws/config file and set the role which needs to be assumed
  #     # - mkdir -p ~/.aws/
  #     # - echo "[profile anotheracc]" >> ~/.aws/config
  #     # - echo "role_arn = arn:aws:iam::$AWS_ACCOUNT_ID:role/ToolsAcctCodePipelineKubernetesRole" >> ~/.aws/config
  #     # - echo "credential_source = EcsContainer" >> ~/.aws/config
  #     # - cat ~/.aws/config
  #     # - aws sts get-caller-identity --profile anotheracc
  #     #2. Install kubectl according to your EKS cluster version
  #     - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/darwin/amd64/kubectl
  #     - chmod +x ./kubectl
  #     - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
  #     - kubectl version --short --client
  #     #3. Create kubeconfig file for your EKS cluster, replace region and name values
  #     #3a. If role is direcly mentioned, uncomment below line and replace role_arn
  #     #- aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $EKS_CLUSTER_NAME --role-arn <role_arn>
  #     - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $EKS_CLUSTER_NAME --profile anotheracc
  #     - cat ~/.kube/config
  #     #4. Set the image tag
  #     - export TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION

  #   build:
  #     commands:
  #       - kubectl get svc